development:
      host: localhost
      adapter: mysql
      database: fedena_development
      port: 3306
      username: root
      password: mypassword

test: &test
      host: localhost
      adapter: mysql
      database: fedena_production
      port: 3306
      username: root
      password: mypassword

production:
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: root
      password: mypassword
cucumber:
  <<: *test
